// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudyPlanner.Data;

#nullable disable

namespace StudyPlanner.Data.Migrations;

[DbContext(typeof(StudyPlannerDbContext))]
[Migration("20260914000000_AddCivilTopicSelection")]
partial class AddCivilTopicSelection
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

        modelBuilder.Entity("StudyPlanner.Core.Models.StudyTopic", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("AllocatedMinutes").HasColumnType("INTEGER");
            b.Property<string>("ArticleNumbers").IsRequired().HasColumnType("TEXT");
            b.Property<TimeSpan>("EndTime").HasColumnType("TEXT");
            b.Property<int>("Mastery").HasColumnType("INTEGER");
            b.Property<string>("Notes").IsRequired().HasColumnType("TEXT");
            b.Property<int>("Priority").HasColumnType("INTEGER");
            b.Property<int>("RowNumber").HasColumnType("INTEGER");
            b.Property<string>("SelectedTopicKeys").IsRequired().HasColumnType("TEXT");
            b.Property<TimeSpan>("StartTime").HasColumnType("TEXT");
            b.Property<int>("StudyDayId").HasColumnType("INTEGER");
            b.Property<int>("Subject").HasColumnType("INTEGER");
            b.Property<string>("Topic").IsRequired().HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("StudyDayId");
            b.ToTable("StudyTopics");
        });
#pragma warning restore 612, 618
    }
}
