// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyPlanner.Data;

#nullable disable

namespace StudyPlanner.Data.Migrations
{
    [DbContext(typeof(StudyPlannerDbContext))]
    partial class StudyPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("StudyPlanner.Core.Models.StudyDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GregorianDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JalaliDateText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GregorianDate")
                        .IsUnique();

                    b.ToTable("StudyDays");
                });

            modelBuilder.Entity("StudyPlanner.Core.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyDayId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("StudyPlanner.Core.Models.StudyTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllocatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedTopicKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyDayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudyDayId");

                    b.ToTable("StudyTopics");
                });

            modelBuilder.Entity("StudyPlanner.Core.Models.StudySession", b =>
                {
                    b.HasOne("StudyPlanner.Core.Models.StudyDay", "StudyDay")
                        .WithMany("Sessions")
                        .HasForeignKey("StudyDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyDay");
                });

            modelBuilder.Entity("StudyPlanner.Core.Models.StudyTopic", b =>
                {
                    b.HasOne("StudyPlanner.Core.Models.StudyDay", "StudyDay")
                        .WithMany("Topics")
                        .HasForeignKey("StudyDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyDay");
                });

            modelBuilder.Entity("StudyPlanner.Core.Models.StudyDay", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
